# Generated by Django 2.1.7 on 2019-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidversion',
            name='version',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
