# Generated by Django 2.1.7 on 2019-03-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20190319_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
