# Generated by Django 2.1.7 on 2019-03-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_job_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
