# Generated by Django 2.1.7 on 2019-04-03 03:26

from django.db import migrations

from apiv1.core.constants import REEF_DEFAULT_MANUFACTURER


def change_manufacturer_name(apps, schema_editor):
    manufacturer_cls = apps.get_model('apiv1', 'Manufacturer')
    try:
        m = manufacturer_cls.objects.get(manufacturer_name='')
        m.manufacturer_name = "ReefDefaultManufacturer"
        m.save()
    except manufacturer_cls.DoesNotExist:
        pass


def reverse_manufacturer_name(apps, schema_editor):
    manufacturer_cls = apps.get_model('apiv1', 'Manufacturer')
    try:
        m = manufacturer_cls.objects.get(manufacturer_name="ReefDefaultManufacturer")
        m.manufacturer_name = ''
        m.save()
    except manufacturer_cls.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('apiv1', '0005_auto_20190329_1152'),
    ]

    operations = [
        migrations.RunPython(
            code=change_manufacturer_name,
            reverse_code=reverse_manufacturer_name
        )
    ]
