# Generated by Django 2.1.7 on 2019-04-04 01:57
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, IntegrityError

from apiv1.module.system.models import System
from apiv1.module.user.models import ReefUser


def add_permission(apps, editor_schema):
    try:  # Ignore data already exist error
        Permission.objects.create(
            name='用户资料管理',
            codename='apiv1.user_management',
            content_type=ContentType.objects.get_for_model(ReefUser)
        )
        Permission.objects.create(
            name='系统升级权限',
            codename='apiv1.upgrade_system',
            content_type=ContentType.objects.get_for_model(System)
        )
        Permission.objects.create(
            name='浏览系统运行日志',
            codename='apiv1.view_system_log',
            content_type=ContentType.objects.get_for_model(System)
        )
    except IntegrityError:
        pass


def reverse(apps, editor_schema):
    Permission.objects.filter(
        codename__in=["apiv1.user_management", "apiv1.upgrade_system", "apiv1.view_system_log"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('apiv1', '0006_change_default_manufacturer_name'),
    ]

    operations = [
        migrations.RunPython(
            code=add_permission,
            reverse_code=reverse
        )
    ]
