# Generated by Django 2.1.7 on 2019-04-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_powerport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempport',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
