# Generated by Django 2.1.7 on 2019-04-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0009_tempport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='created_by_ai_tester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rds',
            name='created_by_sys_job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
