# Generated by Django 2.1.7 on 2019-04-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0012_check_calculate_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.AlterField(
            model_name='devicepower',
            name='power_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devicepower', to='apiv1.PowerPort'),
        ),
    ]
