# Generated by Django 2.1.7 on 2019-06-06 03:59

from django.db import migrations


# noinspection PyPep8Naming
def delete_default_power_port(apps, schema_editor):
    DevicePower = apps.get_model("apiv1", "DevicePower")
    PowerPort = apps.get_model("apiv1", "PowerPort")

    try:
        power_port = PowerPort.objects.get(port="Reef Default PowerPort")
    except PowerPort.DoesNotExist:
        return
    DevicePower.objects.filter(power_port=power_port).update(power_port=None)
    power_port.delete()


# noinspection PyPep8Naming
def add_default_power_port(apps, schema_editor):
    DevicePower = apps.get_model("apiv1", "DevicePower")
    PowerPort = apps.get_model("apiv1", "PowerPort")

    default_power_port, created = PowerPort.objects.get_or_create(
        port="Reef Default PowerPort"
    )

    DevicePower.objects.filter(power_port=None).update(power_port=default_power_port)


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0014_empty_migration'),
    ]

    operations = [
        migrations.RunPython(
            code=delete_default_power_port,
            reverse_code=add_default_power_port
        )
    ]
