# Generated by Django 2.1.7 on 2019-06-06 04:03

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone

from apiv1.module.tboard.models import get_tboard_default_name


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0015_data_migration_for_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='androidversion',
            options={'verbose_name': '安卓版本'},
        ),
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': '机柜'},
        ),
        migrations.AlterModelOptions(
            name='customtag',
            options={'verbose_name': '自定义标签'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '装置'},
        ),
        migrations.AlterModelOptions(
            name='devicechangehistory',
            options={'verbose_name': '装置变更历程'},
        ),
        migrations.AlterModelOptions(
            name='devicecoordinate',
            options={'verbose_name': '装置角点坐标'},
        ),
        migrations.AlterModelOptions(
            name='devicepower',
            options={'verbose_name': '装置电量'},
        ),
        migrations.AlterModelOptions(
            name='devicescreenshot',
            options={'verbose_name': '装置页面截图'},
        ),
        migrations.AlterModelOptions(
            name='devicetemperature',
            options={'verbose_name': '装置温度'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '用例'},
        ),
        migrations.AlterModelOptions(
            name='jobassessment',
            options={'verbose_name': '任务测试评分'},
        ),
        migrations.AlterModelOptions(
            name='jobtestarea',
            options={'verbose_name': '测试用途'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': '制造商'},
        ),
        migrations.AlterModelOptions(
            name='monitorport',
            options={'verbose_name': '相机编号'},
        ),
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'verbose_name': '装置型号'},
        ),
        migrations.AlterModelOptions(
            name='powerport',
            options={'verbose_name': '电量端口'},
        ),
        migrations.AlterModelOptions(
            name='rds',
            options={'verbose_name': '测试结果'},
        ),
        migrations.AlterModelOptions(
            name='rdslog',
            options={'verbose_name': '测试结果日志文件'},
        ),
        migrations.AlterModelOptions(
            name='rdsscreenshot',
            options={'verbose_name': '测试结果截图'},
        ),
        migrations.AlterModelOptions(
            name='reefuser',
            options={'verbose_name': '系统用户'},
        ),
        migrations.AlterModelOptions(
            name='romversion',
            options={'verbose_name': '装置系统版本号'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': '系统'},
        ),
        migrations.AlterModelOptions(
            name='tboard',
            options={'verbose_name': '任务'},
        ),
        migrations.AlterModelOptions(
            name='tempport',
            options={'verbose_name': '温度端口'},
        ),
        migrations.AlterField(
            model_name='androidversion',
            name='version',
            field=models.CharField(max_length=50, unique=True, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cabinet', to='apiv1.System', verbose_name='系统'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='cabinet_name',
            field=models.CharField(max_length=50, verbose_name='机柜名称'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='机柜IP'),
        ),
        migrations.AlterField(
            model_name='customtag',
            name='custom_tag_name',
            field=models.CharField(max_length=50, verbose_name='自定义标签名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ai_occupy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置是否被AI_test用户占用'),
        ),
        migrations.AlterField(
            model_name='device',
            name='android_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='apiv1.AndroidVersion', verbose_name='装置安卓版本'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='apiv1.Cabinet', verbose_name='机柜'),
        ),
        migrations.AlterField(
            model_name='device',
            name='coordinate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='apiv1.DeviceCoordinate', verbose_name='装置四个角点坐标'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu_id',
            field=models.CharField(max_length=50, verbose_name='装置IP地址'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_height',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='装置长度'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_label',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='装置标签'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='Device', max_length=50, verbose_name='装置名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='装置宽度'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='装置IP地址'),
        ),
        migrations.AlterField(
            model_name='device',
            name='monitor_index',
            field=models.ManyToManyField(related_name='device', to='apiv1.MonitorPort', verbose_name='相机编号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='phone_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='apiv1.PhoneModel', verbose_name='装置型号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='rom_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='apiv1.RomVersion', verbose_name='装置系统版本号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='start_time_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置进入系统时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置当前状态'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='android_version_api_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='安卓版本级别'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='android_version_branch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='安卓版本分支'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='android_version_build',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='安卓构建版本'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='android_version_code_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='安卓版本别名'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='android_version_created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='安卓版本资料创建时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='android_version_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='安卓版本ID'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='android_version_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='安卓版本资料最后更新时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='android_version_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='安卓版本号'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='cabinet_cabinet_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='机柜名称'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='cabinet_created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='机柜资料创建时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='cabinet_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='机柜ID'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='cabinet_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='机柜IP地址'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='cabinet_updated_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='机柜资料最后更新时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='cpu_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置CPU ID'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='变更记录时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicechangehistory', to='apiv1.Device', verbose_name='变更资料的装置'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='device_created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='资料创建时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='device_label',
            field=models.CharField(max_length=50, verbose_name='装置标签'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='device_name',
            field=models.CharField(default='Device', max_length=50, verbose_name='装置名称'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='device_updated_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='资料最后更新时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='装置IP地址'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='manufacturer_created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='制造商资料创建时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='manufacturer_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='制造商ID'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='manufacturer_manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='制造商名称'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='manufacturer_updated_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='制造商资料最后更新时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='phone_model_cpu_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置型号CPU名称'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='phone_model_created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='装置型号资料创建时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='phone_model_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='装置型号ID'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='phone_model_phone_model_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置型号名称'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='phone_model_updated_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='装置型号资料最后更新时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='power_port',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置电量端口号'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='rom_version_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='装置系统版本号ID'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='start_time_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置进入系统时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='system_created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='系统资料创建时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='system_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='系统ID'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='system_system_name',
            field=models.CharField(max_length=50, verbose_name='系统名称'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='system_updated_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='系统资料最后更新时间'),
        ),
        migrations.AlterField(
            model_name='devicechangehistory',
            name='temp_port',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置温度端口号'),
        ),
        migrations.AlterField(
            model_name='devicecoordinate',
            name='bottom_left_x',
            field=models.PositiveSmallIntegerField(verbose_name='左下角X轴坐标'),
        ),
        migrations.AlterField(
            model_name='devicecoordinate',
            name='bottom_left_y',
            field=models.PositiveSmallIntegerField(verbose_name='左下角Y轴坐标'),
        ),
        migrations.AlterField(
            model_name='devicecoordinate',
            name='bottom_right_x',
            field=models.PositiveSmallIntegerField(verbose_name='右下角X轴坐标'),
        ),
        migrations.AlterField(
            model_name='devicecoordinate',
            name='bottom_right_y',
            field=models.PositiveSmallIntegerField(verbose_name='右下角Y轴坐标'),
        ),
        migrations.AlterField(
            model_name='devicecoordinate',
            name='upper_left_x',
            field=models.PositiveSmallIntegerField(verbose_name='左上角X轴坐标'),
        ),
        migrations.AlterField(
            model_name='devicecoordinate',
            name='upper_left_y',
            field=models.PositiveSmallIntegerField(verbose_name='左上角Y轴坐标'),
        ),
        migrations.AlterField(
            model_name='devicecoordinate',
            name='upper_right_x',
            field=models.PositiveSmallIntegerField(verbose_name='右上角X轴坐标'),
        ),
        migrations.AlterField(
            model_name='devicecoordinate',
            name='upper_right_y',
            field=models.PositiveSmallIntegerField(verbose_name='右上角Y轴坐标'),
        ),
        migrations.AlterField(
            model_name='devicepower',
            name='battery_file',
            field=models.FileField(upload_to='device', verbose_name='电量文件'),
        ),
        migrations.AlterField(
            model_name='devicepower',
            name='battery_level',
            field=models.PositiveSmallIntegerField(verbose_name='电量值'),
        ),
        migrations.AlterField(
            model_name='devicepower',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicepower', to='apiv1.Cabinet', verbose_name='机柜'),
        ),
        migrations.AlterField(
            model_name='devicepower',
            name='charging',
            field=models.BooleanField(verbose_name='是否在充电'),
        ),
        migrations.AlterField(
            model_name='devicepower',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicepower', to='apiv1.Device', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='devicepower',
            name='power_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devicepower', to='apiv1.PowerPort', verbose_name='电量端口号'),
        ),
        migrations.AlterField(
            model_name='devicepower',
            name='record_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='客户端发送的记录时间'),
        ),
        migrations.AlterField(
            model_name='devicescreenshot',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicescreenshot', to='apiv1.Device', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='devicescreenshot',
            name='screenshot',
            field=models.ImageField(upload_to='device_screenshot', verbose_name='装置截图图片'),
        ),
        migrations.AlterField(
            model_name='devicescreenshot',
            name='snap_timestamp',
            field=models.DateTimeField(verbose_name='装置截图时间'),
        ),
        migrations.AlterField(
            model_name='devicetemperature',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicetemperature', to='apiv1.Cabinet', verbose_name='机柜'),
        ),
        migrations.AlterField(
            model_name='devicetemperature',
            name='description',
            field=models.CharField(max_length=50, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='devicetemperature',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicetemperature', to='apiv1.Device', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='devicetemperature',
            name='record_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录温度时间'),
        ),
        migrations.AlterField(
            model_name='devicetemperature',
            name='temp_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devicetemperature', to='apiv1.TempPort', verbose_name='温度端口'),
        ),
        migrations.AlterField(
            model_name='devicetemperature',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度值'),
        ),
        migrations.AlterField(
            model_name='job',
            name='android_version',
            field=models.ManyToManyField(related_name='job', to='apiv1.AndroidVersion', verbose_name='安卓版本'),
        ),
        migrations.AlterField(
            model_name='job',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='job',
            name='custom_tag',
            field=models.ManyToManyField(related_name='job', to='apiv1.CustomTag', verbose_name='自定义标签'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, verbose_name='用例描述'),
        ),
        migrations.AlterField(
            model_name='job',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='用例是否有效'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='apiv1.JobAssessment', verbose_name='用例测试评分'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deleted',
            field=models.BooleanField(default=False, verbose_name='用例是否被删除'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_label',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='用例标签'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=50, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('UnKnow', 'UnKnow'), ('Sysjob', 'Sysjob'), ('Joblib', 'Joblib')], max_length=10, verbose_name='用例类型'),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone_models',
            field=models.ManyToManyField(related_name='job', to='apiv1.PhoneModel', verbose_name='手机机型'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rom_version',
            field=models.ManyToManyField(related_name='job', to='apiv1.RomVersion', verbose_name='手机系统版本号'),
        ),
        migrations.AlterField(
            model_name='job',
            name='test_area',
            field=models.ManyToManyField(related_name='job', to='apiv1.JobTestArea', verbose_name='用例用途'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='用例最后更新时间'),
        ),
        migrations.AlterField(
            model_name='jobassessment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='测试评分名称'),
        ),
        migrations.AlterField(
            model_name='jobassessment',
            name='value_type',
            field=models.CharField(max_length=50, verbose_name='测试评分类型'),
        ),
        migrations.AlterField(
            model_name='jobtestarea',
            name='description',
            field=models.TextField(db_index=True, unique=True, verbose_name='测试用途描述'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='制造商名称'),
        ),
        migrations.AlterField(
            model_name='monitorport',
            name='port',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='相机编号'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='cpu_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='装置型号CPU名称'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonemodel', to='apiv1.Manufacturer', verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='phone_model_name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='装置型号名称'),
        ),
        migrations.AlterField(
            model_name='powerport',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerport', to='apiv1.Device', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='powerport',
            name='port',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='电量端口'),
        ),
        migrations.AlterField(
            model_name='powerport',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电量端口当前状态'),
        ),
        migrations.AlterField(
            model_name='rds',
            name='created_by_ai_tester',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='是否AItest用户创建'),
        ),
        migrations.AlterField(
            model_name='rds',
            name='created_by_sys_job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='是否系统任务'),
        ),
        migrations.AlterField(
            model_name='rds',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rds', to='apiv1.Device', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='rds',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='用例结束时间'),
        ),
        migrations.AlterField(
            model_name='rds',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rds', to='apiv1.Job', verbose_name='用例'),
        ),
        migrations.AlterField(
            model_name='rds',
            name='job_assessment_value',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='测试评分'),
        ),
        migrations.AlterField(
            model_name='rds',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='用例开始时间'),
        ),
        migrations.AlterField(
            model_name='rds',
            name='tboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rds', to='apiv1.TBoard', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='rdslog',
            name='file_name',
            field=models.CharField(max_length=50, verbose_name='测试结果日志文件名称'),
        ),
        migrations.AlterField(
            model_name='rdslog',
            name='log_file',
            field=models.FileField(upload_to='rds_logs', verbose_name='测试结果日志文件'),
        ),
        migrations.AlterField(
            model_name='rdslog',
            name='rds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdslog', to='apiv1.Rds', verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='rdsscreenshot',
            name='file_name',
            field=models.CharField(max_length=50, verbose_name='测试结果截图名称'),
        ),
        migrations.AlterField(
            model_name='rdsscreenshot',
            name='img_file',
            field=models.ImageField(upload_to='screen_shot', verbose_name='测试结果截图'),
        ),
        migrations.AlterField(
            model_name='rdsscreenshot',
            name='rds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdsscreenshot', to='apiv1.Rds', verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='rdsscreenshot',
            name='thumbs_file',
            field=models.ImageField(blank=True, null=True, upload_to='screen_shot', verbose_name='测试结果截压缩图'),
        ),
        migrations.AlterField(
            model_name='romversion',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='romversion', to='apiv1.Manufacturer', verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='romversion',
            name='version',
            field=models.CharField(max_length=50, unique=True, verbose_name='装置系统版本号'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='系统IP地址'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_name',
            field=models.CharField(max_length=50, verbose_name='系统名称'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tboard', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='board_name',
            field=models.CharField(default=get_tboard_default_name, max_length=50, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='board_stamp',
            field=models.DateTimeField(db_index=True, unique=True, verbose_name='创建任务时间'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='device',
            field=models.ManyToManyField(related_name='tboard', to='apiv1.Device', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='finished_flag',
            field=models.BooleanField(default=False, verbose_name='任务是否结束'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='job',
            field=models.ManyToManyField(related_name='tboard', to='apiv1.Job', verbose_name='用例'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='repeat_time',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='任务重复次数'),
        ),
        migrations.AlterField(
            model_name='tempport',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='温度的描述信息'),
        ),
        migrations.AlterField(
            model_name='tempport',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tempport', to='apiv1.Device', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='tempport',
            name='port',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='温度端口号'),
        ),
        migrations.AlterField(
            model_name='tempport',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='温度端口状态'),
        ),
    ]
