# Generated by Django 2.1.7 on 2019-06-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0016_auto_20190606_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tboard',
            name='success_ratio',
            field=models.FloatField(null=True),
        ),
    ]
