# Generated by Django 2.1.7 on 2019-06-06 04:49

from django.db import migrations
from django.db.models import Count


# noinspection PyPep8Naming
def calculate_tboard_success_ratio(apps, schema_editor):
    TBoard = apps.get_model("apiv1", "TBoard")
    Rds = apps.get_model("apiv1", "Rds")

    for tboard in TBoard.objects.all():
        rdss = Rds.objects.values("job_assessment_value").annotate(count=Count("*")).filter(
            job_assessment_value__in=["0", "1"]).filter(tboard=tboard).order_by("-count")
        success = failed = 0
        for rds in rdss:
            if rds['job_assessment_value'] == "0":
                success = rds['count']
            elif rds['job_assessment_value'] == "1":
                failed = rds['count']

        TBoard.objects.filter(id=tboard.id).update(
            success_ratio=round(success / (success + failed), 2) if success + failed > 0 else 0)


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('apiv1', '0017_tboard_success_ratio'),
    ]

    operations = [
        migrations.RunPython(
            code=calculate_tboard_success_ratio,
            reverse_code=do_nothing
        )
    ]
