# Generated by Django 2.1.7 on 2019-06-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0019_auto_20190610_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rds',
            name='tboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rds', to='apiv1.TBoard', verbose_name='任务'),
        ),
    ]
