# Generated by Django 2.1.7 on 2019-09-04 01:28

import apiv1.module.tboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0021_auto_20190626_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='instance_port',
            field=models.IntegerField(null=True, verbose_name='用以记录与设备绑定实例的端口号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='Device', max_length=50, null=True, verbose_name='装置名称'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='board_name',
            field=models.CharField(default=apiv1.module.tboard.models.get_tboard_default_name, max_length=32, verbose_name='任务名称'),
        ),
    ]
