# Generated by Django 2.1.7 on 2019-09-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0022_auto_20190904_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='power_lower_limit',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='手机电量下限限制'),
        ),
        migrations.AddField(
            model_name='job',
            name='power_upper_limit',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='手机电量上限限制'),
        ),
        migrations.AlterField(
            model_name='job',
            name='android_version',
            field=models.ManyToManyField(related_name='job', to='apiv1.AndroidVersion', verbose_name='安卓版本限制'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('UnKnow', 'UnKnow'), ('Sysjob', 'Sysjob'), ('Joblib', 'Joblib'), ('Uniq', 'Uniq')], max_length=10, verbose_name='用例类型'),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone_models',
            field=models.ManyToManyField(related_name='job', to='apiv1.PhoneModel', verbose_name='手机机型限制'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rom_version',
            field=models.ManyToManyField(related_name='job', to='apiv1.RomVersion', verbose_name='手机系统版本号限制'),
        ),
    ]
