# Generated by Django 2.1.7 on 2019-09-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0023_auto_20190902_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBoardJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='用例在任务中的顺序')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tboardjob', to='apiv1.Job', verbose_name='用例关联')),
                ('tboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tboardjob', to='apiv1.TBoard', verbose_name='任务关联')),
            ],
        ),
    ]
