# Generated by Django 2.1.7 on 2019-09-03 07:46

from django.db import migrations


# noinspection PyPep8Naming
def create_through_relations(apps, schema_editor):
    """
    Moving relations from apiv1_tboard_job to apiv1_tboardjob
    """
    Job = apps.get_model('apiv1', 'Job')
    TBoardJob = apps.get_model('apiv1', 'TBoardJob')

    seq = {}
    for job in Job.objects.all().order_by("id"):
        tboard_jobs = []
        print(f"processing job {job.id}...")
        for tboard in job.tboard.all():
            if tboard.id in seq:
                order = seq[tboard.id]
            else:
                order = seq[tboard.id] = 0
            tboard_jobs.append(TBoardJob(
                tboard=tboard,
                job=job,
                order=order
            ))
            seq[tboard.id] += 1
        TBoardJob.objects.bulk_create(tboard_jobs, batch_size=500)


# noinspection PyPep8Naming
def clear_through_relations(apps, schema_editor):
    """
    Moving relations from apiv1_tboardjob to apiv1_tboard_job
    """
    TBoardJob = apps.get_model('apiv1', 'TBoardJob')
    Job = apps.get_model('apiv1', 'Job')

    for job in Job.objects.values_list("id", flat=True).order_by("id"):
        tboards = []
        print(f"Moving relations for job {job}")
        for tboardjob in TBoardJob.objects.filter(job_id=job):
            tboards.append(
                tboardjob.tboard_id
            )
        try:
            Job.objects.get(id=job).tboard.add(*tboards)
        except Job.DoesNotExist:
            print(f"Warning! cannot find job {job}")
            continue

    TBoardJob.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('apiv1', '0024_tboardjob'),
    ]

    operations = [
        migrations.RunPython(
            code=create_through_relations,
            reverse_code=clear_through_relations
        )
    ]
