# Generated by Django 2.1.7 on 2019-09-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0025_migrate_tboardjob_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tboard',
            name='job',
        ),
    ]
