# Generated by Django 2.1.7 on 2019-09-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0026_remove_tboard_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='tboard',
            name='job',
            field=models.ManyToManyField(related_name='tboard', through='apiv1.TBoardJob', to='apiv1.Job', verbose_name='用例'),
        ),
    ]
