# Generated by Django 2.2 on 2019-09-18 06:19

from django.db import migrations, models
from apiv1.core.constants import POWER_CONSUMPTION_ERROR_CODE


class Migration(migrations.Migration):
    dependencies = [
        ('apiv1', '0027_tboard_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='power_consumption',
            field=models.SmallIntegerField(
                help_text='记录该用例运行过程中的电量变化，目前只支持Uniq类的用例，不支持的用例产生的Rds该字段值为null，'
                f'合法的值范围为-100~100。若资料异常无法计算出该值，则以{POWER_CONSUMPTION_ERROR_CODE}记录',
                null=True, verbose_name='耗电量'),
        ),
    ]
