# Generated by Django 2.2 on 2019-09-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0028_rds_power_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auto_test',
            field=models.BooleanField(default=False, verbose_name='系统是否自动分派任务给该设备'),
        ),
    ]
