# Generated by Django 2.2 on 2019-10-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0031_fill_device_auto_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='temp_consumption',
            field=models.DecimalField(decimal_places=2, help_text='记录该用例运行过程中的温度变化，目前只支持Uniq类的用例，不支持的用例产生的Rds该字段值为null，合法的值范围为-199.99~199.99。若资料异常无法计算出该值，则以-999.99记录', max_digits=5, null=True, verbose_name='温度差'),
        ),
    ]
