# Generated by Django 2.2 on 2019-10-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0032_rds_temp_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='typical_job_temp_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='此温度差由Coral计算，这里只负责更新记录。不支持的用例产生的Rds该字段值为null。不同job开始记录温度时间不同', max_digits=5, null=True, verbose_name='特定job的温度差'),
        ),
        migrations.AlterField(
            model_name='tboard',
            name='success_ratio',
            field=models.FloatField(default=None, null=True),
        ),
    ]
