# Generated by Django 2.2 on 2019-12-05 03:12

from django.db import migrations


def change_manufacturer_name(apps, schema_editor):

    # reef会在 0001_initial.py文件下初始化一笔 manufacturer数据
    # 历史原因厂商名默认小米，现在可以在apiv1/core/constants.py里可以配置manufacturer_name，因此先注释这段代码

    # manufacturer_cls = apps.get_model('apiv1', 'Manufacturer')
    # try:
    #     m = manufacturer_cls.objects.get(manufacturer_name='ReefDefaultManufacturer')
    #     m.manufacturer_name = 'XiaoMi'
    #     m.save()
    # except manufacturer_cls.DoesNotExist:
    #     pass

    pass


def reverse_manufacturer_name(apps, schema_editor):
    manufacturer_cls = apps.get_model('apiv1', 'Manufacturer')
    try:
        m = manufacturer_cls.objects.get(manufacturer_name='XiaoMi')
        m.manufacturer_name = 'ReefDefaultManufacturer'
        m.save()
    except manufacturer_cls.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('apiv1', '0033_auto_20191021_1548'),
    ]

    operations = [
        migrations.RunPython(
            code=change_manufacturer_name,
            reverse_code=reverse_manufacturer_name
        )
    ]
