# Generated by Django 2.2 on 2019-12-12 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0036_auto_20191212_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='机柜IP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='apiv1.Cabinet', verbose_name='机柜'),
        ),
    ]
