# Generated by Django 2.2 on 2019-12-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0038_auto_20191215_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaneView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='PaneView名称', max_length=64, unique=True, verbose_name='PaneView名称')),
                ('type', models.CharField(choices=[('matrix', 'matrix'), ('map', 'map')], help_text='PaneView的类型(matrix, map)', max_length=16, verbose_name='PaneView类型')),
                ('width', models.PositiveIntegerField(help_text='PaneView的宽度，对于matrix类型的PaneView来说，代表的是有多少个column。对于map类型来说，代表px', verbose_name='PaneView宽度')),
                ('height', models.PositiveIntegerField(help_text='PaneView的高度，对于matrix类型的PaneView来说，代表的是有多少个row。对于map类型来说，代表px', verbose_name='PaneView高度')),
                ('cabinet', models.ForeignKey(help_text='PaneView所属机柜', on_delete=django.db.models.deletion.PROTECT, related_name='paneviews', to='apiv1.Cabinet', verbose_name='机柜')),
            ],
        ),
        migrations.CreateModel(
            name='PaneSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(help_text='于paneview中的row位置', verbose_name='row')),
                ('col', models.PositiveIntegerField(help_text='于paneview中的col位置', verbose_name='col')),
                ('status', models.CharField(choices=[('ok', 'ok'), ('empty', 'empty'), ('error', 'error')], default='empty', help_text='Slot状态(ok, empty, error)', max_length=16, verbose_name='Slot状态')),
                ('device', models.OneToOneField(help_text='当前与slot关联的设备', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paneslot', to='apiv1.Device', verbose_name='关联设备')),
                ('paneview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paneslots', to='apiv1.PaneView')),
            ],
        ),
    ]
