# Generated by Django 2.2 on 2020-01-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0039_add_paneview_paneslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tboard',
            name='board_stamp',
            field=models.DateTimeField(verbose_name='创建任务时间'),
        ),
    ]
