# Generated by Django 2.2 on 2020-01-02 08:59
import datetime

from django.db import migrations
from django.db.models import Count


def nothing(apps, schema_editor):
    pass


def delete_same_board_stamp(apps, schema_editor):
    """
    将tboard board_stamp字段设置为唯一值, 相同的时间添加index个小时
    """

    tboard_model = apps.get_model('apiv1', 'TBoard')
    for tboard_data in tboard_model.objects.values("board_stamp").annotate(count=Count("id")):
        if tboard_data['count'] >= 2:
            for index, tboard in enumerate(tboard_model.objects.filter(board_stamp=tboard_data['board_stamp'])):
                tboard.board_stamp = tboard.board_stamp - datetime.timedelta(days=index + 1000)
                tboard.save()


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0040_auto_20200102_1537'),
    ]

    operations = [
        migrations.RunPython(
            code=nothing,
            reverse_code=delete_same_board_stamp
        ),
    ]
