# Generated by Django 2.2 on 2020-03-11 08:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0042_tboard_is_to_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tempport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WoodenBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='硬件模块名称')),
                ('type', models.CharField(choices=[('power', 'power'), ('temp', 'temp')], max_length=150, verbose_name='硬件模块类型')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='木盒ip')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='木盒配置文件')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woodenbox', to='apiv1.Cabinet', verbose_name='机柜')),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.AddField(
            model_name='powerport',
            name='woodenbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerport', to='apiv1.WoodenBox'),
        ),
        migrations.AddField(
            model_name='tempport',
            name='woodenbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tempport', to='apiv1.WoodenBox'),
        ),
    ]
