# Generated by Django 2.2 on 2020-03-21 03:11
import random
import string

from django.db import migrations
from django.db.models import Count


def random_str():
    return ''.join(random.choices(string.ascii_letters + string.digits, k=5))


def custom_tag_name_to_unique(apps, schema_editor):
    custom_tag_cls = apps.get_model('apiv1', 'CustomTag')

    custom_tags = custom_tag_cls.objects.values('custom_tag_name'). \
        annotate(count=Count('custom_tag_name')). \
        filter(count__gt=1)

    for custom_tag in custom_tags:
        objs = custom_tag_cls.objects.filter(custom_tag_name=custom_tag['custom_tag_name'])[1:]
        for obj in objs:
            obj.custom_tag_name = custom_tag['custom_tag_name'] + random_str()
            obj.save()


def reverse(apps, editor_schema):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('apiv1', '0043_auto_20200311_1626'),
    ]

    operations = [
        migrations.RunPython(
            code=custom_tag_name_to_unique,
            reverse_code=reverse
        )
    ]
