# Generated by Django 2.2 on 2020-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0044_custom_tag_name_to_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='custom_tag_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='自定义标签名称'),
        ),
    ]
