# Generated by Django 2.2 on 2020-03-21 07:48

from django.db import migrations


def process_not_uniq_data(apps, schema_editor):
    from django.db import connection
    woodenbox_cls = apps.get_model('apiv1', 'WoodenBox')

    cursor = connection.cursor()
    cursor.execute("""
        select a.id,a.ip,a.cabinet_id,b.id,b.ip,b.cabinet_id 
        from apiv1_woodenbox as a 
        join apiv1_woodenbox as b 
        on a.ip=b.ip and a.cabinet_id=b.cabinet_id and a.id != b.id
    """)
    ret = cursor.fetchall()
    for aid, aip, ac, bid, bip, bc in ret:
        # 如果发现重复的ip, cabinet_id组合，删除后面创建的木盒
        woodenbox_cls.objects.filter(id=max(aid, bid)).delete()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('apiv1', '0045_auto_20200321_1548'),
    ]

    operations = [
        migrations.RunPython(
            code=process_not_uniq_data,
            reverse_code=reverse_code,
            atomic=False
        ),
        migrations.AlterUniqueTogether(
            name='woodenbox',
            unique_together={('name', 'type'), ('ip', 'cabinet')},
        ),
    ]
