# Generated by Django 2.2 on 2020-08-24 03:28

from django.db import migrations, connection
from django.db.models import Count

from apiv1.module.rds.models import Rds


def reverse():
    pass


def delete_unique_together_error_data(apps, schema_editor):
    sql = f"""
            DELETE 
        FROM
            apiv1_rdsscreenshot 
        WHERE
            rds_id IN (
            SELECT
                r.ID 
            FROM
                ( SELECT job_id, device_id, start_time FROM apiv1_rds GROUP BY job_id, device_id, start_time HAVING COUNT ( 'id' ) > 1 ) AS abc
                LEFT JOIN apiv1_rds AS r ON abc.job_id = r.job_id 
                AND abc.device_id = r.device_id 
                AND abc.start_time = r.start_time 
            );
        DELETE 
        FROM
            apiv1_rdslog 
        WHERE
            rds_id IN (
            SELECT
                r.ID 
            FROM
                ( SELECT job_id, device_id, start_time FROM apiv1_rds GROUP BY job_id, device_id, start_time HAVING COUNT ( 'id' ) > 1 ) AS abc
                LEFT JOIN apiv1_rds AS r ON abc.job_id = r.job_id 
                AND abc.device_id = r.device_id 
                AND abc.start_time = r.start_time 
            );
        DELETE 
        FROM
            apiv1_rds 
        WHERE
            ID IN (
            SELECT
                r.ID 
            FROM
                ( SELECT job_id, device_id, start_time FROM apiv1_rds GROUP BY job_id, device_id, start_time HAVING COUNT ( 'id' ) > 1 ) AS abc
                LEFT JOIN apiv1_rds AS r ON abc.job_id = r.job_id 
                AND abc.device_id = r.device_id 
                AND abc.start_time = r.start_time 
            )
    """
    with connection.cursor() as c:
        c.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0047_auto_20200514_1512_squashed_0060_devicecutcoordinate'),
    ]

    operations = [
        migrations.RunPython(
            code=delete_unique_together_error_data,
            reverse_code=reverse
        ),
        migrations.AlterUniqueTogether(
            name='rds',
            unique_together={('device', 'job', 'start_time')},
        ),
    ]

