# Generated by Django 2.2.10 on 2020-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0061_auto_20200824_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='inner_job',
            field=models.ManyToManyField(blank=True, related_name='job', to='apiv1.Job', verbose_name='子用例'),
        ),
    ]
