# Generated by Django 2.2 on 2021-04-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0063_auto_20200828_1902_squashed_0072_auto_20210329_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='end_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='性能测试结束点'),
        ),
        migrations.AddField(
            model_name='rds',
            name='picture_count',
            field=models.IntegerField(default=0, verbose_name='图片数量'),
        ),
        migrations.AddField(
            model_name='rds',
            name='start_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='性能测试开始点'),
        ),
        migrations.AddField(
            model_name='rds',
            name='time_per_unit',
            field=models.FloatField(blank=True, null=True, verbose_name='性能测试单位耗时'),
        ),
        migrations.AddField(
            model_name='rds',
            name='url_prefix',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='图片url前缀'),
        ),
    ]
