# Generated by Django 2.2 on 2021-04-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0073_auto_20210413_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecutcoordinate',
            name='desktop_x',
            field=models.FloatField(blank=True, null=True, verbose_name='桌面键x坐标'),
        ),
        migrations.AddField(
            model_name='devicecutcoordinate',
            name='desktop_y',
            field=models.FloatField(blank=True, null=True, verbose_name='桌面键y坐标'),
        ),
        migrations.AddField(
            model_name='devicecutcoordinate',
            name='menu_x',
            field=models.FloatField(blank=True, null=True, verbose_name='菜单键x坐标'),
        ),
        migrations.AddField(
            model_name='devicecutcoordinate',
            name='menu_y',
            field=models.FloatField(blank=True, null=True, verbose_name='菜单键y坐标'),
        ),
        migrations.AddField(
            model_name='devicecutcoordinate',
            name='return_x',
            field=models.FloatField(blank=True, null=True, verbose_name='返回键x坐标'),
        ),
        migrations.AddField(
            model_name='devicecutcoordinate',
            name='return_y',
            field=models.FloatField(blank=True, null=True, verbose_name='返回键y坐标'),
        ),
    ]
