# Generated by Django 2.2 on 2021-04-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0074_auto_20210416_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecutcoordinate',
            name='inside_under_right_x',
            field=models.FloatField(blank=True, null=True, verbose_name='内框右下x坐标'),
        ),
        migrations.AlterField(
            model_name='devicecutcoordinate',
            name='inside_under_right_y',
            field=models.FloatField(blank=True, null=True, verbose_name='内框右下y坐标'),
        ),
        migrations.AlterField(
            model_name='devicecutcoordinate',
            name='inside_upper_left_x',
            field=models.FloatField(blank=True, null=True, verbose_name='内框左上x坐标'),
        ),
        migrations.AlterField(
            model_name='devicecutcoordinate',
            name='inside_upper_left_y',
            field=models.FloatField(blank=True, null=True, verbose_name='内框左上y坐标'),
        ),
        migrations.AlterField(
            model_name='devicecutcoordinate',
            name='outside_under_right_x',
            field=models.FloatField(blank=True, null=True, verbose_name='外框右下x坐标'),
        ),
        migrations.AlterField(
            model_name='devicecutcoordinate',
            name='outside_under_right_y',
            field=models.FloatField(blank=True, null=True, verbose_name='外框右下y坐标'),
        ),
        migrations.AlterField(
            model_name='devicecutcoordinate',
            name='outside_upper_left_x',
            field=models.FloatField(blank=True, null=True, verbose_name='外框左上x坐标'),
        ),
        migrations.AlterField(
            model_name='devicecutcoordinate',
            name='outside_upper_left_y',
            field=models.FloatField(blank=True, null=True, verbose_name='外框左上y坐标'),
        ),
    ]
