# Generated by Django 2.2 on 2021-04-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0075_auto_20210423_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='subsidiary_device_count',
        ),
        migrations.RemoveField(
            model_name='subsidiarydevice',
            name='devices',
        ),
        migrations.AddField(
            model_name='subsidiarydevice',
            name='custom_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subsidiarydevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiarydevice', to='apiv1.Device', verbose_name='关联主设备'),
        ),
        migrations.AddField(
            model_name='subsidiarydevice',
            name='phone_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiarydevice', to='apiv1.PhoneModel', verbose_name='装置型号'),
        ),
        migrations.AddField(
            model_name='subsidiarydevice',
            name='status',
            field=models.CharField(default='unbound', max_length=50, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='subsidiarydevice',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='subsidiarydevice',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='相对于主设备的编号'),
        ),
    ]
