# Generated by Django 2.2 on 2021-05-10 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0077_subsidiarydevice_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPGather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='app名称')),
            ],
        ),
        migrations.CreateModel(
            name='SIMCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.CharField(max_length=30, verbose_name='运营商')),
                ('is_volte', models.BooleanField(default=True, verbose_name='是否有volte服务')),
                ('status', models.CharField(choices=[('busy', 'busy'), ('idle', 'idle')], default='idle', max_length=30, verbose_name='SIM卡状态')),
                ('phone_number', models.CharField(max_length=30, unique=True, verbose_name='手机号码')),
                ('order', models.SmallIntegerField(blank=True, null=True, verbose_name='SIM卡编号')),
                ('history_relevance', models.CharField(blank=True, max_length=30, verbose_name='历史关联设备')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simcard', to='apiv1.Device', verbose_name='绑定设备')),
                ('subsidiary_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simcard', to='apiv1.SubsidiaryDevice', verbose_name='绑定僚机')),
            ],
            options={
                'verbose_name_plural': 'SIM 卡',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='账号id')),
                ('username', models.CharField(max_length=30, verbose_name='账号名称')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('status', models.CharField(choices=[('busy', 'busy'), ('idle', 'idle')], default='idle', max_length=15, verbose_name='账号状态')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='绑定手机号码')),
                ('head_portrait_name', models.CharField(blank=True, max_length=30, verbose_name='头像名称')),
                ('crony', models.CharField(blank=True, max_length=100, verbose_name='好友')),
                ('max_login_num', models.SmallIntegerField(verbose_name='最大同时登陆数')),
                ('app_name', models.CharField(blank=True, max_length=30, verbose_name='账号归属app名称')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='apiv1.APPGather')),
                ('device', models.ManyToManyField(blank=True, related_name='account', to='apiv1.Device', verbose_name='关联设备')),
                ('subsidiary_device', models.ManyToManyField(blank=True, related_name='account', to='apiv1.SubsidiaryDevice', verbose_name='关联僚机设备')),
            ],
            options={
                'verbose_name_plural': '账号',
                'unique_together': {('name', 'app')},
            },
        ),
    ]
