# Generated by Django 2.2 on 2021-05-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0078_account_appgather_simcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='lose_frame_point',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='丢帧点'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_second_type',
            field=models.CharField(blank=True, choices=[('TimeJob', 'TimeJob'), ('SmoothJob', 'SmoothJob')], max_length=10, null=True, verbose_name='用例二级分类'),
        ),
    ]
