# Generated by Django 2.2 on 2021-05-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0079_auto_20210512_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiarydevice',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='ip地址'),
        ),
    ]
