# Generated by Django 2.2 on 2021-06-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0081_auto_20210602_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='inner_job',
        ),
        migrations.RemoveField(
            model_name='jobresourcefile',
            name='job',
        ),
    ]
