# Generated by Django 2.2 on 2021-06-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0082_auto_20210617_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='机柜类型'),
        ),
        migrations.AddField(
            model_name='job',
            name='cabinet_type',
            field=models.CharField(max_length=50, null=True, verbose_name='机柜类型'),
        ),
    ]
