# Generated by Django 2.2 on 2021-07-20 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0083_auto_20210618_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='请用文字描述发生的问题,如异常请写出错误码和对应错误的unit,如果是页面异常请描述对应页面异常位置', verbose_name='bug 描述')),
                ('happened_time', models.DateTimeField(verbose_name='发生时间')),
                ('status', models.CharField(choices=[('未处理', '未处理'), ('已解决', '已解决')], default='未处理', max_length=50)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Cabinet', verbose_name='机柜编号')),
                ('device', models.ForeignKey(blank=True, help_text='idle&busy设备显示备注名，offline设备显示devicelabel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Device', verbose_name='使用设备')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Job', verbose_name='使用用例')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reporter', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
            ],
            options={
                'verbose_name': 'Bug上报',
                'verbose_name_plural': 'Bug上报',
            },
        ),
    ]
