# Generated by Django 2.2 on 2021-07-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0084_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug', to='apiv1.Cabinet', verbose_name='机柜编号'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='device',
            field=models.ForeignKey(blank=True, help_text='idle&busy设备显示备注名，offline设备显示devicelabel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug', to='apiv1.Device', verbose_name='使用设备'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug', to='apiv1.Job', verbose_name='使用用例'),
        ),
    ]
