# Generated by Django 2.2 on 2021-07-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0086_job_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='level',
            field=models.CharField(choices=[('1级', '1级'), ('2级', '2级'), ('3级', '3级'), ('4级', '4级')], default='4级', max_length=50),
        ),
    ]
