# Generated by Django 2.2 on 2021-09-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0088_auto_20210802_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='绑定手机号码'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=100, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='jobflow',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用例执行流名称'),
        ),
    ]