# Generated by Django 2.2 on 2021-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0089_auto_20210915_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_group',
            field=models.SmallIntegerField(default=1, verbose_name='unit所属类型'),
        ),
    ]