# Generated by Django 2.2 on 2021-10-11 03:37

from django.db import migrations, models
from apiv1.module.resource.models import TGuard


def create_tguard(apps, schema_editor):
    # 添加系统级 TGuard词组
    t_guard = ["确定", "同意", "同意并继续", "同意并使用", "暂不开启", "允许", "好的", "开始", "继续", "我知道了", "跳过",
               "以后再说", "仅使用期间允许", "仅在使用中允许", "本次运行允许", "始终允许", "下一步", "暂不升级", "不了，谢谢",
               "不了谢谢", "知道了", "不开启", "仅在使用此应用时允许"]

    obj_list = [TGuard(name=i, is_system=True) for i in t_guard]
    if obj_list:
        TGuard.objects.bulk_create(obj_list)


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0090_unit_unit_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='词组名称')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否为系统固定词组')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=create_tguard,
            reverse_code=reverse_code
        )
    ]
