# Generated by Django 2.2 on 2021-10-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0091_tguard'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='filter',
            field=models.CharField(blank=True, choices=[('serious', 'serious')], max_length=50, null=True, verbose_name='rds筛选标注'),
        ),
    ]
