# Generated by Django 2.2 on 2021-10-26 09:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0092_rds_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='测试集名称')),
                ('job_count', models.IntegerField(default=0, verbose_name='job数量')),
                ('duration_time', models.BigIntegerField(default=0, verbose_name='预计耗时')),
                ('cabinet_version', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='用例所属机柜类型')),
                ('job', models.ManyToManyField(related_name='testgather', to='apiv1.Job', verbose_name='关联job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
