# Generated by Django 2.2 on 2021-11-19 06:46

from django.db import migrations, models
import django.utils.timezone
import django.db.models.deletion
from apiv1.module.resource.models import APPGather


def create_app_name_list(apps, schema_editor):
    app_name_list = [
        'OPPO',
        '小米',
        '爱奇艺',
        '腾讯视频',
        '哔哩哔哩',
        '优酷视频',
        '西瓜视频',
        'QQ音乐',
        '酷狗音乐',
        '网易云音乐',
        '抖音短视频',
        '快手',
        '快手极速版',
        '抖音火山版',
        '抖音极速版',
        '好看视频',
        'YY',
        '虎牙直播',
        '斗鱼',
        '映客直播',
        '全民K歌',
        '唱吧',
        'QQ浏览器',
        'UC浏览器',
        '百度',
        '微博',
        '知乎',
        '百度贴吧',
        '小红书',
        '脉脉',
        '微博极速版',
        '钉钉',
        '微信',
        'QQ',
        'QQ阅读',
        '微信读书',
        '掌阅',
        '作业帮',
        '小猿搜题',
        '今日头条',
        '腾讯新闻',
        '网易新闻',
        '搜狐新闻',
        '趣头条',
        '今日头条极速版',
        '一点资讯',
        '滴滴出行',
        '高德地图',
        '百度地图',
        '腾讯地图',
        '去哪儿旅行',
        '携程旅行',
        '飞猪旅行',
        '马蜂窝旅游',
        '京东',
        '拼多多',
        '手机淘宝',
        '手机天猫',
        '苏宁易购',
        '唯品会',
        '饿了吗',
        '美团外卖',
        '招商银行',
        '支付宝',
        'QQ邮箱',
        '网易邮箱',
        '139邮箱',
        '企业微信',
        'WPS Office',
        '58同城',
        '美团'
    ]
    app_obj_list = [APPGather(name=i) for i in app_name_list]
    if app_name_list:
        APPGather.objects.bulk_create(app_obj_list)


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0093_testgather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='max_login_num',
        ),
        migrations.AddField(
            model_name='appgather',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appgather',
            name='max_login_num',
            field=models.SmallIntegerField(default=1, verbose_name='最大同时登陆数'),
        ),
        migrations.AddField(
            model_name='appgather',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.RunPython(
            code=create_app_name_list,
            reverse_code=reverse_code
        )
    ]
