# Generated by Django 2.2 on 2021-12-01 07:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0095_auto_20211201_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='app_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='app信息记录'),
        ),
        migrations.AddField(
            model_name='rds',
            name='rom_version_const',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='rds创建时设备系统版本号'),
        ),
    ]
