# Generated by Django 2.2 on 2022-02-16 07:31

from django.db import migrations, models

def run_code(apps, schema):
    Device = apps.get_model('apiv1', "Device")
    device_queryset = Device.objects.exclude(status='offline').distinct('phone_model')
    for device in device_queryset:
        device.phone_model.height_resolution = device.device_height
        device.phone_model.width_resolution = device.device_width
        device.phone_model.save()


def run_reverse_code(apps, editor_schema):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0098_auto_20220118_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='height_resolution',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='高度分辨率'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='width_resolution',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='宽度分辨率'),
        ),
        migrations.RunPython(
            code=run_code,
            reverse_code=run_reverse_code
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_height',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_width',
        ),
    ]
