# Generated by Django 2.2 on 2022-03-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0099_auto_20220216_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='tboard',
            name='job_random_order',
            field=models.BooleanField(default=False, verbose_name='tboard中用例顺序是否随机'),
        ),
    ]
