# Generated by Django 2.2 on 2022-03-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0100_tboard_job_random_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGatherShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.TestGather')),
            ],
            options={
                'verbose_name_plural': '测试集项目关联',
            },
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='项目名称')),
                ('test_gather', models.ManyToManyField(through='apiv1.TestGatherShip', to='apiv1.TestGather', verbose_name='关联测试集')),
            ],
            options={
                'verbose_name_plural': '测试项目',
            },
        ),
        migrations.AddField(
            model_name='testgathership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.TestProject'),
        ),
        migrations.AlterUniqueTogether(
            name='testgathership',
            unique_together={('gather', 'project')},
        ),
    ]
