# Generated by Django 2.2 on 2022-03-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0101_auto_20220309_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodelcustomcoordinate',
            name='x_coordinate',
            field=models.FloatField(blank=True, null=True, verbose_name='x坐标'),
        ),
        migrations.AlterField(
            model_name='phonemodelcustomcoordinate',
            name='y_coordinate',
            field=models.FloatField(blank=True, null=True, verbose_name='y坐标'),
        ),
        migrations.AlterField(
            model_name='testgathership',
            name='gather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testgathership', to='apiv1.TestGather'),
        ),
        migrations.AlterField(
            model_name='testgathership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testgathership', to='apiv1.TestProject'),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='test_gather',
            field=models.ManyToManyField(related_name='testproject', through='apiv1.TestGatherShip', to='apiv1.TestGather', verbose_name='关联测试集'),
        ),
    ]
