# Generated by Django 2.2 on 2022-03-30 02:50

from django.db import migrations, models
import django.db.models.deletion
from apiv1.module.device.models import PowerPort, PowerStrategy


def init_power_strategy_data(apps, schema_editor):
    queryset = PowerPort.objects.all()
    for power_port in queryset:
        PowerStrategy.objects.create(**{
            "power_port": power_port,
            "min_value": 30,
            "max_value": 100,
            "is_default": True
        })


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0102_auto_20220325_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.SmallIntegerField(verbose_name='电量最小值')),
                ('max_value', models.SmallIntegerField(verbose_name='电量最大值')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='策略开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='策略结束时间')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认策略')),
                ('power_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerstrategy', to='apiv1.PowerPort', verbose_name='电量端口')),
            ],
        ),
        migrations.RunPython(
            code=init_power_strategy_data
        )
    ]
