# Generated by Django 2.2 on 2022-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0103_powerstrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tboard',
            name='test_gather_name',
            field=models.CharField(default='', max_length=350, verbose_name='测试集名称合集'),
        ),
    ]
