# Generated by Django 2.2 on 2022-05-12 03:36

from django.db import migrations, models
import django.db.models.deletion

from apiv1.module.abnormity.models import AbnormityType

"""
添加新异常类型数据
"""


def add_abnormity_type_data(apps, schema_editor):
    AbnormityType.objects.bulk_create(
        [
            AbnormityType(title='ANR', code=2),
            AbnormityType(title='Crash', code=3),
            AbnormityType(title='Exception', code=4)
        ]
    )


def delete_abnormity_type_data(apps, schema_editor):
    AbnormityType.objects.filter(code__in=[2, 3, 4]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0105_device_status_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormity',
            name='abnormity_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormity', to='apiv1.AbnormityPolicy', verbose_name='异常规则'),
        ),
        migrations.CreateModel(
            name='AbnormityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='abnormity_logs/%Y_%m_%d', verbose_name='测试结果日志文件')),
                ('name', models.CharField(max_length=100, verbose_name='测试结果日志文件名称')),
                ('type', models.CharField(max_length=50, verbose_name='用例资源文件类型')),
                ('abnormity_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormitydetail', to='apiv1.AbnormityDetail', verbose_name='异常详情')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=add_abnormity_type_data,
            reverse_code=delete_abnormity_type_data
        )
    ]
