# Generated by Django 2.2 on 2022-06-02 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0106_auto_20220512_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='m_location_x',
            field=models.FloatField(blank=True, null=True, verbose_name='m_location x 坐标'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='m_location_y',
            field=models.FloatField(blank=True, null=True, verbose_name='m_location y 坐标'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='m_location_z',
            field=models.FloatField(blank=True, null=True, verbose_name='m_location z 坐标'),
        ),
        migrations.AlterField(
            model_name='abnormitylog',
            name='abnormity_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormitylog', to='apiv1.AbnormityDetail', verbose_name='异常详情'),
        ),
    ]
