# Generated by Django 2.2 on 2022-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0107_auto_20220602_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rds',
            name='url_prefix',
        ),
        migrations.AddField(
            model_name='rdsscreenshot',
            name='is_resource_file',
            field=models.BooleanField(default=False),
        ),
    ]
