# Generated by Django 2.2 on 2022-06-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0108_auto_20220615_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='custom_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='自定义编号'),
        ),
        migrations.AddField(
            model_name='subsidiarydevice',
            name='custom_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='自定义编号'),
        ),
    ]
