# Generated by Django 2.2 on 2022-07-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0109_auto_20220629_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unit_group',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='使用unit类型'),
        ),
    ]
