# Generated by Django 2.2 on 2022-08-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0110_job_unit_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('UnKnow', 'UnKnow'), ('Sysjob', 'Sysjob'), ('Joblib', 'Joblib'), ('PerfJob', 'PerfJob'), ('Uniq', 'Uniq'), ('InnerJob', 'InnerJob'), ('ComboJob', 'ComboJob'), ('MultiDevice', 'MultiDevice')], max_length=10, verbose_name='用例类型'),
        ),
    ]
