# Generated by Django 2.2 on 2022-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0111_auto_20220811_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tboard',
            name='belong',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='第三方创建者'),
        ),
    ]
