# Generated by Django 2.2 on 2022-09-06 10:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0112_tboard_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_support_parameter',
            field=models.BooleanField(default=False, verbose_name='job是否支持传参'),
        ),
        migrations.CreateModel(
            name='JobParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('parameter', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='job参数')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_parameter', to='apiv1.Job', verbose_name='用例')),
                ('tboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_parameter', to='apiv1.TBoard', verbose_name='任务关联')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
