# Generated by Django 2.2 on 2022-11-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0113_auto_20220906_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBoardStatisticsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_path', models.CharField(max_length=350, verbose_name='文件路径')),
                ('tboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tboardstatisticsresult', to='apiv1.TBoard', verbose_name='任务关联')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
